#!/bin/sh

# Creates a firefox instance with a temporary profile
firefox_create_instance () {
  # Create a directory to hold new instances
  local instances_dir="/tmp/firefox_temporary_instances"
  if [ ! -e $instances_dir ]; then
    mkdir $instances_dir
  fi

  # Find a random empty directory
  local destination_dir="$instances_dir/firefox_instance_$RANDOM"
  while [ -e $destination_dir ]; do
    destination_dir="$instances_dir/firefox_instance_$RANDOM"
  done

  mkdir $destination_dir
  chmod 0700 $destination_dir

  # Copy over real profile and remove the locks + session data
  local profiles=("$HOME/.mozilla/firefox/*.default")
  local src_dir="${profiles[0]}"

  cp -r $src_dir/browser-extension-data $destination_dir
  cp -r $src_dir/extension{s,-data} $destination_dir
  cp -r $src_dir/chrome $destination_dir
  cp $src_dir/extensions.{ini,json} $destination_dir
  cp $src_dir/extensions-settings.json $destination_dir
  cp $src_dir/addonStartup.json.lz4 $destination_dir
  cp $src_dir/{addons,blocklist*}.json $destination_dir
  cp $src_dir/prefs.js $destination_dir
  cp $src_dir/search.json* $destination_dir

  firefox --profile $destination_dir --no-remote --private-window "about:newtab"&
  wait $!
  rm -r $destination_dir # Remove the directory once the instance is closed

  # Remove the instances directory if this was the last instance
  if [ -z "$(ls -A $instances_dir)" ]; then
    rmdir $instances_dir
  fi
}


firefox_create_instance
